version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - analyzer
      - db
      - redis

  analyzer:
    build: ./analyzer
    volumes:
      - ./analyzer:/analyzer
      - gcloud-config:/root/.config/gcloud
    ports:
      - "9000:9000"

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

  terraform:
    build: ./terraform
    volumes:
      - ./terraform:/terraform
      - gcloud-config:/root/.config/gcloud
    deploy:
      replicas: 0

  gcloud:
    image: google/cloud-sdk
    entrypoint: gcloud
    volumes:
      - gcloud-config:/root/.config/gcloud
    deploy:
      replicas: 0

volumes:
  db-data:
  gcloud-config:
