version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_APPLICATION_CREDENTIALS=/backend/credentials.json
    depends_on:
      - analyzer
      - db
      - redis

  analyzer:
    build: ./analyzer
    volumes:
      - ./analyzer:/analyzer
    ports:
      - "9000:9000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/analyzer/credentials.json

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
