version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  analyzer:
    build: ./analyzer
    volumes:
      - ./analyzer:/analyzer
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
