version: "3"
services:
  backend:
    image: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - analyzer
      - db
      - redis

  analyzer:
    image: analyzer
    ports:
      - "9000:9000"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: cloudbuild
