steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/analyzer", "."]
    dir: "analyzer"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/analyzer"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "analyzer",
        "--image",
        "gcr.io/$PROJECT_ID/analyzer",
        "--region",
        "asia-northeast1",
        "--no-traffic",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "services",
        "update-traffic",
        "analyzer",
        "--region",
        "asia-northeast1",
        "--to-latest",
      ]

images:
  - "gcr.io/$PROJECT_ID/analyzer"
